---
- name: Install java8
  apt:
     name: openjdk-8-jdk
     state: present
     update_cache: yes
  when: ansible_os_family == 'Debian'

- name: debug
  debug:
    var: "{{ ansible_os_family }}"

- name: Install java8 on Redhat
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"


- name: set java_home
  shell: echo JAVA_HOME is $JAVA_HOME
  environment:
    JAVA_HOME: "{{ Debian_java_home }}"
  when: ansible_os_family == 'Debian'
  register: shellout

- name: set java_home
  shell: echo JAVA_HOME is $JAVA_HOME
  environment:
    JAVA_HOME: "{{ Redhat_java_home }}"
  when: ansible_os_family == 'RedHat'
  register: shellout

- name: check java_home
  debug:
    var: shellout
